### ISSUE TITLE
Need a daemon stop command

### ISSUE THREAD

**Issue by tusharr** [Locale/localeapp#107]
Most background daemons have commands to stop/start the server. Localeapp is missing the stop command. I have to manually find the pid and kill the daemon

**Comment by maesitos** [comment]
Any solution for this?

`$ kill `pidof localeapp``
The above code can be a problem if you have stage and production in the same machine.

I'm doing:
`kill $(cat tmp/pids/localeapp.pid)`
but since the daemon doesn't remove localeapp.pid before being closed it could close other proces that started to use the same pid.
