### ISSUE TITLE
Is gettext supported?

### ISSUE THREAD

**Issue by brauliobo** [Locale/localeapp#173]
I've to push the `po` dir with `localeapp push po` and nothing got pushed.

**Comment by michaelbaudino** [comment]
Hi @brauliobo,

Unfortunately for you, no: we do not support Gettext and will probably never support it.
We think gettext is flawed because it does not allow you to change content in the source language, it does not support namespacing correctly enough and it is not native with Rails. It has a few advantages, though (like having more readable source code), but we decided to focus on the the more powerful solution.

**Comment by brauliobo** [comment]
Thanks @michaelbaudino. I agree rails' yaml files are way better, but unfortunetely not everybody on the project I work thinks this way, so we still support po files.
