### ISSUE TITLE
Feature request for left hand side folder tree: file symbol for translations

### ISSUE THREAD

**Issue by ncri** [Locale/localeapp#37]
I was suggesting this small but highly valuable feature a while ago:

It would be great if translation leaf keys would use the file symbol rather than a folder symbol on the lefthand side translation key tree. That way one could easily distinguish between "folders" (=nested translations) or keys that directly hold a translations (the yaml trees leaf nodes). A useful ordering would then be "folders" first then "files".

Opinions?

Would be great to see this added ;-)

**Comment by kksure** [comment]
Hi,

Great to know this is being developed. We are soon going live, and this feature will help us a lot with maintaining our translations.

Any eta on this one?

**Comment by michaelbaudino** [comment]
Hi @kksure this feature has actually already been implemented:

![screenshot-www localeapp com 2015-03-13 12-01-39](https://cloud.githubusercontent.com/assets/1447321/6637296/06585a46-c979-11e4-9d07-924a2b6c9a0f.png)

Except that we finally decided to keep alphabetical order, as it turned out to be more efficient to use.

Is that what you are expecting ? Or am I missing something ?

Also, this is the gem repository, would you mind continuing this conversation by opening a ticket in the in-app support system ?
